### ISSUE TITLE
Add scripts to validate, plan and deploy the IaC

### ISSUE THREAD

**Issue by ViniciusSouza** [Azure/data-landing-zone#106]
**Describe the solution you'd like**

Using PowerShell scripts to validate (ARM template toolkit), plan (what-if) and deploy will help to have a clean pipeline (ADO/GitHub) and also allow to use/test it locally with the same confidence.

**Comment by marvinbuss** [comment]
The what-if step will be added, once it is supported here: https://github.com/Azure/arm-deploy/issues/71#issuecomment-887386732
