### ISSUE TITLE
Issue to deploy metadata services [Retryable Error]

### ISSUE THREAD

**Issue by renepajta** [Azure/data-landing-zone#156]
**Describe the bug**
Cannot proceed with operation because resource /subscriptions/ed780b0d-a01c-4a39-982b-949f0c8c84e3/resourceGroups/rpdlz01-dev-network/providers/Microsoft.Network/virtualNetworks/rpdlz01-dev-vnet/subnets/ServicesSubnet used by resource /subscriptions/ed780b0d-a01c-4a39-982b-949f0c8c84e3/resourceGroups/rpdlz01-dev-metadata/providers/Microsoft.Network/networkInterfaces/rpdlz01-dev-sqlserver001-private-endpoint.nic.ccece0ec-b039-4bf9-9945-5538cae5196b is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation.

**Steps to reproduce**

1.  Deploy Data Management Zone
2.  Deploy Data Landing Zone without SHIR

**Screenshots**
![image](https://user-images.githubusercontent.com/6043628/127778578-914cb7b4-4ae4-44c7-a232-e14abc4811de.png)
![image](https://user-images.githubusercontent.com/6043628/127778586-409b1ac3-7e6e-4e6a-9b64-bd735c3e5c56.png)
![image](https://user-images.githubusercontent.com/6043628/127778605-e33777e2-0e8a-4f7c-97f2-4300e15b57e4.png)

**Comment by marvinbuss** [comment]
Hi @renepajta,
Thanks for submitting this. Did this happen repeatedly? Did you deploy multiple Landing Zones over the past days and this this error happen each time?

**Comment by marvinbuss** [comment]
@renepajta Can you try the steps described here and report whether the issue is reproducible?
https://github.com/Azure/data-landing-zone/discussions/158#discussioncomment-1129091

**Comment by renepajta** [comment]
Yes, I have deployed the zone multiple times before the issue occurred. 

I haven't been able to reproduce the error and I have encountered deployment errors with other components as well e.g. storage services as well but simple re-deployment fixed that. 

Therefore, I would mark it as completed.

**Comment by marvinbuss** [comment]
@renepajta What was the storage error about? Did the Private Endpoint deployment fail or did the storage service itself fail?
I have reached out to the PG to analyze the private endpoint issue.

**Comment by marvinbuss** [comment]
Update: We are starting to investigate this issue.
