### ISSUE TITLE
DL Zone deployment Uk south failed with DM Zone in japan east

### ISSUE THREAD

**Issue by fabianjogschies** [Azure/data-landing-zone#161]
Correlation id: 842ddec7-2250-425e-91be-e81b6d3c46fe

DLzone Region: Uk South
DM Zone Region: Japan Eas

![image](https://user-images.githubusercontent.com/6885215/127514181-967afde2-3470-44af-9cd3-13504f4889e3.png)

Network Service failure:
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "Bei der Ressourcenbereitstellung ist mindestens ein Fehler aufgetreten. Listen Sie die Bereitstellungsvorgänge auf, um Details anzuzeigen. Weitere Informationen zur Verwendung finden Sie unter https://aka.ms/DeployOperations.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"RemotePeeringIsDisconnected\",\r\n    \"message\": \"Das Peering \\\"/subscriptions/73996236-393b-4e42-b339-9d61ab0e572c/resourceGroups/dlzone-dev-network/providers/Microsoft.Network/virtualNetworks/dlzone-dev-vnet/virtualNetworkPeerings/dmzonedev-dev-vnet\\\" kann nicht erstellt oder aktualisiert werden, weil Remotepeering \\\"/subscriptions/73996236-393b-4e42-b339-9d61ab0e572c/resourceGroups/dmzonedev-dev-network/providers/Microsoft.Network/virtualNetworks/dmzonedev-dev-vnet/virtualNetworkPeerings/dlzone-dev-vnet\\\", das auf das übergeordnete virtuelle Netzwerk \\\"/subscriptions/73996236-393b-4e42-b339-9d61ab0e572c/resourceGroups/dlzone-dev-network/providers/Microsoft.Network/virtualNetworks/dlzone-dev-vnet\\\" verweist, sich im Zustand \\\"Getrennt\\\" befindet. Aktualisieren Sie das Remotepeering, oder erstellen Sie es neu, um es wieder in den Zustand \\\"Initiiert\\\" zu versetzen. Das Peering wechselt in den Zustand \\\"Getrennt\\\", wenn das virtuelle Remotenetzwerk oder das Remotepeering gelöscht und neu erstellt wird.\",\r\n    \"details\": []\r\n  }\r\n}"
            }
        ]
    }
}

how to reproduce:

1.Deploy Data Management Zone succesfully
2. Deploy DL Zone in a Region
3. Delete DL Zone in a region
4. Create DLZone with same prefix in another region

**Comment by renepajta** [comment]
I would vote for the option #2 and document to check for former VNET peering with the same deployments.

**Comment by AnalyticJeremy** [comment]
I believe that the second option is the better approach.  It's important to keep the naming convention as clean as possible to help customers navigate all of the resources that get created.
To address the issue, we should provide clear guidance on everything that needs to be done when deleting a landing zone.  We could also extend our suggested script to handle this automatically.

**Comment by marvinbuss** [comment]
Thanks for the feedback @AnalyticJeremy & @renepajta!

@AnalyticJeremy Could you please work on the guidance for users and add this to the thread here: https://github.com/Azure/data-landing-zone/discussions/151. We should probably extend the cleanup script and in addition we could add a docs page that describes the cleanup process.

**Comment by marvinbuss** [comment]
@AnalyticJeremy Could you please add this [here](https://github.com/Azure/data-landing-zone/discussions/151) so that this happens automatically for users?

**Comment by AnalyticJeremy** [comment]
I have updated our delete script to handle this automatically.

**Comment by marvinbuss** [comment]
I will close this issue, as @AnalyticJeremy has added a new cleanup script that handles these scenarios automatically (https://github.com/Azure/data-landing-zone/discussions/151#discussioncomment-1087979).
In addition, I have added more guidance to the original post (https://github.com/Azure/data-landing-zone/discussions/151#discussion-3480974).
