### ISSUE TITLE
Vnet deployment when conditioned databricks nsg

### ISSUE THREAD

**Issue by xigyenge** [Azure/data-landing-zone#18]
The deployment is not taking into consideration the false variable defined below which is conditioning the deployment of the databricks nsg:
` "deployDatabricksNsg": {
            "type": "bool",
            "defaultValue": false `

Error received: 
 "code": "InvalidResourceReference", "message": "Resource /subscriptions/2150d511-458f-43b9-8691-6819ba2e6c7b/resourceGroups/DN001-NETWORK/providers/Microsoft.Network/networkSecurityGroups/DN001-DATABRICKS-NSG referenced by resource /subscriptions/2150d511-458f-43b9-8691-6819ba2e6c7b/resourceGroups/dn001-network/providers/Microsoft.Network/virtualNetworks/dn001-vnet was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.", "details": [ *** "code": "NotFound", "message": "Resource /subscriptions/2150d511-458f-43b9-8691-6819ba2e6c7b/resourceGroups/DN001-NETWORK/providers/Microsoft.Network/networkSecurityGroups/DN001-DATABRICKS-NSG not found

Workaround - Deployed the databricsk nsg without conditioning it with the option of not.

**Comment by marvinbuss** [comment]
I think we can close this for now. I just introduced the boolean because of some issues that occurred in the past. However, this is fixed now. We can still keep the boolean if the issue reoccurs with different ADB settings.

**Comment by xigyenge** [comment]
> I think we can close this for now. I just introduced the boolean because of some issues that occurred in the past. However, this is fixed now. We can still keep the boolean if the issue reoccurs with different ADB settings.

Ok. Let's discuss it as well offline. :)
