### ISSUE TITLE
Feature Request: Install SHIR via Custom Data

### ISSUE THREAD

**Issue by marvinbuss** [Azure/data-landing-zone#188]
**Describe the solution you'd like**
Use the custom data feature of Azure VMs instead of pointing to a storage account for installing the SHIR Gateway onto a VMSS. This will improve the security of the setup and remove a storage account that currently needs to be deployed as part of ESA. In addition, it will simplify the CI/CD pipelines of the Data Landing Zone.

**Comment by esbran** [comment]
"commandToExecute": "powershell -ExecutionPolicy unrestricted -NoProfile -NonInteractive -command \"cp c:/azuredata/customdata.bin c:/azuredata/install.ps1; c:/azuredata/install.ps1\""

**Comment by marvinbuss** [comment]
> "commandToExecute": "powershell -ExecutionPolicy unrestricted -NoProfile -NonInteractive -command "cp c:/azuredata/customdata.bin c:/azuredata/install.ps1; c:/azuredata/install.ps1""

Here are more details:
https://stackoverflow.com/questions/45273561/unable-to-execute-custom-data-in-azure-vm-from-terraform
