### ISSUE TITLE
Template failing on privateDnsZoneGroups when deploying to Data Management Zone without Azure Firewall and Private DNS Zones

### ISSUE THREAD

**Issue by baatch** [Azure/data-landing-zone#203]
**Describe the bug**
Deployment of templates failes on privateDnsZoneGroups for serveral resources if deployed to a Data Management Zone without Azure Firewall and Private DNS Zones.

Error message:
```
{
    "status": "Failed",
    "error": {
        "code": "LinkedAuthorizationFailed",
        "message": "The client 'c37c27fa-5b67-4a0d-8d50-bbad8ecf70e2' with object id 'c37c27fa-5b67-4a0d-8d50-bbad8ecf70e2' has permission to perform action 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write' on scope '/subscriptions/3a517887-399a-4758-9d12-e055e804eb9d/resourcegroups/lexdlz01-dev-logging/providers/Microsoft.Network/privateEndpoints/lexdlz01-dev-vault003-private-endpoint/privateDnsZoneGroups/default'; however, it does not have permission to perform action 'Microsoft.Network/privateDnsZones/join/action' on the linked scope(s) '/subscriptions/48fc3def-3fff-4933-afcf-cdcc2a8da06a/resourceGroups/lexdmz-dev-global-dns/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net' or the linked scope(s) are invalid."
    }
}
```

Please add option or suggestion on how to deploy Data Landing Zone to a Data Management Zone that is deployed without Azure Firewall and Private DNS Zones. See discussion on ([https://github.com/Azure/data-management-zone/discussions/211])

**Steps to reproduce**

1.  Deploy Data Management Zone without Azure Firewall and Private DNS Zones by setting parameter enableDnsAndFirewallDeployment to false in params.dev.json
2.  Deploy Data Landing Zone according to instructions for Azure Devops.

**Screenshots**
![image](https://user-images.githubusercontent.com/16446781/139433297-78d1b834-1822-4bc1-bd4c-74e58151c5c3.png)

![image](https://user-images.githubusercontent.com/16446781/139433169-c60208ca-209d-4d23-831c-0e49b067b0a0.png)

**Comment by baatch** [comment]
> The DNS Contributor role needs to be assigned to the `global-dns` resource group as described here: ![image](https://user-images.githubusercontent.com/34542414/139472295-8c183bf5-ac77-425f-8816-c09321d93d0b.png) https://github.com/Azure/data-landing-zone/blob/main/docs/EnterpriseScaleAnalytics-ServicePrincipal.md#adding-additional-role-assigments


Thank you for pointing out the wrong resource group. I added the role assignment to the correct resource group global-dns and now I get this error instead:

```
{
    "status": "Failed",
    "error": {
        "code": "InvalidPrivateDnsZoneIds",
        "message": "Private Dns Zone group /subscriptions/3a517887-399a-4758-9d12-e055e804eb9d/resourceGroups/lexdlz01-dev-logging/providers/Microsoft.Network/privateEndpoints/lexdlz01-dev-vault003-private-endpoint/privateDnsZoneGroups/default has invalid private dns zone ids .",
        "details": []
    }
}
```

![image](https://user-images.githubusercontent.com/16446781/139487609-ca3075ed-c873-42ce-ac09-237cdccf6869.png)

![image](https://user-images.githubusercontent.com/16446781/139487683-490f1524-d83e-4d20-8732-96692c6ab602.png)


![image](https://user-images.githubusercontent.com/16446781/139487655-1931a75f-4749-4e37-b593-e3ee0c5e98b2.png)

**Comment by marvinbuss** [comment]
Hi @baatch,
Sorry for my late response! Are you deploying through GitHub Actions, Azure DevOps or Portal experience?

If you deploy via GitHub Actions or Azure DevOps, which reference have you defined here:
https://github.com/Azure/data-landing-zone/blob/691046b6b70cf54d90329cb480af061a6a23d6b4/infra/params.dev.json#L82-L84

**Comment by marvinbuss** [comment]
Hi @baatch,
Any updates? :)

**Comment by marvinbuss** [comment]
Hi @baatch,
Sorry for the late response! So, you have created a resource group with the name `global-dns` manually inside the Data Management Zone subscription and you have manually assigned the RBAC role of the Service Principle?
So there are no Private DNS Zones existing like shown below?
![image](https://user-images.githubusercontent.com/34542414/141757592-74bade38-0bcc-4f29-b0b5-4f8268d1e0f3.png)

**Comment by marvinbuss** [comment]
> @marvinbuss
> 
> Sorry for late reply, life got busy.
> 
> this is in the params.dev.json file:
> 
> ```
> "privateDnsZoneIdKeyVault": {
>             "value": "/subscriptions/48fc3def-3fff-4933-afcf-cdcc2a8da06a/resourceGroups/lexdmz-dev-global-dns/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"
>         }
> ```
> 
> But since I deployed Data Management Zone by setting parameter enableDnsAndFirewallDeployment to false in params.dev.json there is no Global DNS?

The question is, does the Private DNS Zone referenced here exist?

**Comment by marvinbuss** [comment]
Hi @baatch,
Any updates or should we close this issue?

**Comment by baatch** [comment]
> 

Let's close it. I don't have the time to follow up at the moment.

**Comment by marvinbuss** [comment]
Please reopen this issue when you have the time to investigate this. Happy to look into this and troubleshoot with you.
