### ISSUE TITLE
Bug Report: supported regions list outdated

### ISSUE THREAD

**Issue by mariekekortsmit** [Azure/data-landing-zone#208]
It seems like the officially supported deployment regions:

- (Asia Pacific) Japan East
- (Europe) France Central
- (Europe) Germany West Central
- (US) Central US

are not an option as Azure Purview is not available in those. Or am I missing something here?

**Comment by mariekekortsmit** [comment]
This might only be an issue in the Data Management Zones repo, as there is no Purview instance deployed as part of the Data Landing Zone.

**Comment by sasever** [comment]
It is a valid point for data management zone but there is actually a workaround where we deploy purview to northeurope if selected region does not support purview deployment. To reflect the change I will add this info to the docs marking the related regions.

**Comment by sasever** [comment]
Fixed the docs with Purview default deployment region update #231 on data-management-zone repo
