### ISSUE TITLE
Feature Request: Alternative Default Setup for DNS A-Records in "Deploy to Azure" button

### ISSUE THREAD

**Issue by mariekekortsmit** [Azure/data-landing-zone#212]
**Describe the solution you'd like**
Current "Deploy to Azure" button has default setup "DNS A-Records are deployed through Azure Policy" > Yes. However, in the most simple setup you'd want to set it as follows: 
![image](https://user-images.githubusercontent.com/32355947/142887781-2b033aeb-d163-4649-b19d-0fc6ec923f5c.png)

therefore I would suggest changing the default to "No" here.

**Comment by marvinbuss** [comment]
Thanks @mariekekortsmit! I will work on this tomorrow. 🚀
