### ISSUE TITLE
Deployment of storage accounts fails due to invalid values for request parameters for NetworkRuleSet

### ISSUE THREAD

**Issue by abdale** [Azure/data-landing-zone#253]
### Deployment Mode

Deploy To Azure

### Steps to reproduce

Standard deployment of DLZ using deploy to Azure button results in storage accounts failing to be deployed.

### Error Message

```json
Screenshot below
```

### Screenshots

![image](https://github.com/Azure/data-landing-zone/assets/8771696/30947380-31fd-42f6-922d-edfeffd168fe)

![image](https://github.com/Azure/data-landing-zone/assets/8771696/900315f7-5138-4178-9a74-8d42f3da902e)

![image](https://github.com/Azure/data-landing-zone/assets/8771696/3ae1ec0b-7b05-4760-93cd-5371990c8d97)

![image](https://github.com/Azure/data-landing-zone/assets/8771696/ae82086e-df75-4028-93c1-5613b555fbe3)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-landing-zone/blob/main/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
@abdale Can you please share with me what you have entered here:
![image](https://github.com/Azure/data-landing-zone/assets/34542414/42af6cd4-1f0f-4d3e-bc88-726dc9bdd556)
Thanks!

**Comment by abdale** [comment]
... I left it blank as this was the only DLZ being deployed.
