### ISSUE TITLE
Variables Created by "GeneratePipelineVariables.ps1" Are Not Available in Pipeline

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-landing-zone#62]
**Describe the bug**
In the ADO deployment pipeline, we are calling the `code/GeneratePipelineVariables.ps1` script.  It takes a JSON string output from a previous tasks, unwinds the properties within the JSON object, and creates variables for each property.  However, these variables are not being properly exported and cannot be referenced by subsequent tasks in the pipeline.

**Example**
A "generate variables" task will produce output like this:

```
Retrieved input: {"storageAccountId":{"type":"String","value":"/subscriptions/17588eb2-2943-461a-ab3f-00a3ceac3112/resourceGroups/jpdlz-integration/providers/Microsoft.Storage/storageAccounts/jpdlzartifactsa001"},"storageAccountName":{"type":"String","value":"jpdlzartifactsa001"},"storageAccountContainerName":{"type":"String","value":"scripts"}}
Setting output 'storageAccountId'
Setting output 'storageAccountName'
Setting output 'storageAccountContainerName'
```

Given this result, I should be able to reference `$(storageAccountName)` in my pipeline.  However, when the Pipeline executes a task trying to use that variable, it will fail.  AzDO doesn't even try to expand the variable.  For example, I will get an error message like:  `Storage account: $(storageAccountName) not found.`

This behavior is exhibited on a variety of task types.

**WORK AROUND!**
We don't need to generate pipeline variables.  We can just reference members of the original variable.  From the example above, `$(storageAccountName) ` does not work... but **`$(storageDetails.storageAccountName.value)`** does work.

**Comment by AnalyticJeremy** [comment]
This issue could be caused by the manner in which the `GeneratePipelineVariables.ps1` script is called.  It is run as a "AzureCLI" task.

In contrast, the `GeneratePassword.ps1` script (which successfully exports its output as a variable pipeline) is executed as a "PowerShell" task. 

I have not done any experiments to test this hypothesis, but it does seem plausible.

**Comment by marvinbuss** [comment]
Hi @AnalyticJeremy,
The ARM Task was changed late last year, which is why you see this behavior.
https://github.com/microsoft/azure-pipelines-tasks/blob/9e3ea8cc7454ae5a1275cc9a1deca4481b4173b0/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/DeploymentScopeBase.ts

I will update it accordingly.

**Comment by marvinbuss** [comment]
I will fix this by latest Monday morning. I have new solutions ready and I will push them later this weekend or Monday morning!
