### ISSUE TITLE
AzureFileCopy Task Fails

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-landing-zone#63]
**Describe the bug**

When deploying the data landing zone via ADO Pipelines, an "AzureFileCopy" task is used to upload a PowerShell script to blob storage for use in the SHIR deployment process.  However, this task fails with the following error:

```
##[error]Storage account: "jpdlzartifactsa001" not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.
```

- The storage account "jpdlzartifactsa001" exists in the same subscription to which the ADO ARM Service Connection is attached.
- The service principal (which was also used to create the storage account) has been granted "Storage Blob Data Contributor" access to the storage account.
- The same result is observed when using both v3 and v4 of the "AzureFileCopy" task

Microsoft support forums have several reports from both internal and external users who have experienced the same problem.  The PG says "it works on my machine" and no one has identified a cause or a solution.  Examples:
- [AzureFileCopy not working](https://developercommunity.visualstudio.com/content/problem/1249903/azurefilecopy-not-working.html)
- [Unable to connect to storage account inside AzureFileCopy@2-task of Azure DevOps Pipelines](https://developercommunity.visualstudio.com/content/problem/587476/unable-to-connect-to-storage-account-inside-azuref.html)
- [AzureDevOps: Service Connection permissions for using AzureFileCopy task to write to Azure blob storage](https://developercommunity.visualstudio.com/content/problem/1225871/azuredevops-service-connection-permissions-for-usi.html)
- [azure file copy task error](https://developercommunity.visualstudio.com/content/problem/1127993/azure-file-copy-task-error-2.html)
- [Existing storage account not found from Copy task](https://developercommunity.visualstudio.com/content/problem/446511/existing-storage-account-not-found-from-copy-task.html)
- [Storage Account not found](https://developercommunity.visualstudio.com/content/problem/1034531/storage-account-not-found.html)

**Suggested Solution**
Forget the "AzureFileCopy" task.  Use a PowerShell script like we do in the GitHub Actions pipeline:
```
"Uploading file to Storage Account 001"
$storageAccount = Get-AzStorageAccount -ResourceGroupName "${{ env.AZURE_RESOURCE_GROUP_NAME_INTEGRATION }}" -Name "${{ steps.artifact_storage_001_deployment.outputs.storageAccountName }}"
$ctx = $storageAccount.Context
Set-AzStorageBlobContent -Context $ctx -Container "${{ steps.artifact_storage_001_deployment.outputs.storageAccountContainerName }}" -File "infra/SelfHostedIntegrationRuntime/installSHIRGateway.ps1" -Blob "installSHIRGateway.ps1" -Force
```

This will keep the ADO pipeline more consistent with the GitHub Action, and it will allow us to avoid a troublesome black-box task type.

**Comment by marvinbuss** [comment]
I will fix this by latest Monday morning. I have new solutions ready and I will push them later this weekend or Monday morning! 
This will make the solution consistent across ADO and GH.
